name: Deploy Workflow

on:
  push:
      branches:
          - master

jobs:
 my-workflow-job-4:
      uses: zeallearn/reusable_workflow/.github/workflows/workflow-template.yml@master
      with:
        ENVIRONMENT: myenvironment
