name: Workflow Template with Fix

on:
  workflow_call:
    secrets:
      MY_SECRET: 
        required: false
            
jobs:
    my-job:
        name: my-job
        runs-on: ubuntu-latest

        env:
            MY_SECRET: ${{ secrets.MY_SECRET }}

        steps:
            - uses: actions/checkout@v2

            - run : |
                echo 'printing envs'
                env
