name: Deploy Workflow test

on:
  push:
      branches:
          - feature

jobs:
 my-workflow-job-4:
      uses: zeallearn/reusable_workflow/.github/workflows/workflow-template.yml@main
      with:
        ENVIRONMENT: myenvironment